namespace: kuttle

operator:
  image:
    repository: ktlai/kop
    tag: v1.0.0
    pullPolicy: IfNotPresent

crds:
  create: true

ingress:
  enabled: true
  host: app.ktl.ai

license:
  token: "FREE"
