# Default values for KTL DevPortal

replicaCount: 1

cloudProvider: ""  # "", "eks"

service:
  type: ClusterIP
  port: 80
  annotations: {}

ingress:
  enabled: false
  className: ""
  host: ""
  annotations: {}

serviceAccount:
  create: true
  name: "ktl-operator"

klient:
  image:
    repository: "public.ecr.aws/j3b6v1h4/klient"
    tag: "latest"
    pullPolicy: "IfNotPresent"

kop:
  image:
    repository: "public.ecr.aws/j3b6v1h4/kop"
    tag: "latest"
    pullPolicy: "IfNotPresent"