cloudProvider: "eks"  # "eks", "gke", or "aks"

serviceAccount:
  name: "ktl-operator"

service:
  type: "LoadBalancer"
  annotations:
    eks:
      service.beta.kubernetes.io/aws-load-balancer-type: "external"
      alb.ingress.kubernetes.io/scheme: "internet-facing"
      alb.ingress.kubernetes.io/group.name: "ktl-alb"
    gke:
      cloud.google.com/load-balancer-type: "External"
    aks:
      service.beta.kubernetes.io/azure-load-balancer-internal: "false"

ingress:
  enabled: false
  className: ""
  host: "app.ktl.ai"
  annotations:
    eks:
      alb.ingress.kubernetes.io/scheme: "internet-facing"
    gke:
      kubernetes.io/ingress.class: "gce"
    aks:
      kubernetes.io/ingress.class: "azure/application-gateway"

klient:
  image:
    repository: "ktlai/klient"
    tag: "latest"
    pullPolicy: "Always"

kop:
  image:
    repository: "ktlai/kop"
    tag: "latest"
    pullPolicy: "Always"
