cloudProvider: "eks"  # Currently only supporting AWS EKS

accountId: ""  # If not provided, Helm will attempt to infer it
serviceAccount:
  name: "aws-load-balancer-controller"
  roleArn: ""  # If empty, Helm will generate based on accountId

service:
  type: "LoadBalancer"
  annotations:
    eks:
      service.beta.kubernetes.io/aws-load-balancer-type: "external"
      alb.ingress.kubernetes.io/scheme: "internet-facing"
      alb.ingress.kubernetes.io/group.name: "ktl-alb"

ingress:
  enabled: false
  className: "alb"
  host: "app.ktl.ai"
  annotations:
    eks:
      alb.ingress.kubernetes.io/scheme: "internet-facing"

klient:
  image:
    repository: "ktlai/klient"
    tag: "latest"
    pullPolicy: "Always"

kop:
  image:
    repository: "ktlai/kop"
    tag: "latest"
    pullPolicy: "Always"
