apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: app.ktl.ai
spec:
  group: ktl.ai
  names:
    kind: Env
    plural: envs
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              appVersion:
                type: string
          status:
            type: object
            properties:
              phase:
                type: string
              details:
                type: object
                properties:
                  services:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        status:
                          type: string