apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: envs.ktl.ai
spec:
  group: ktl.ai
  names:
    kind: Env
    plural: envs
    singular: env
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              services:
                type: array
                items:
                  type: object
                  properties:
                    service_name:
                      type: string
                      description: "Name of the service"
                    cpu:
                      type: integer
                      description: "CPU allocation (in millicores)"
                    memory:
                      type: integer
                      description: "Memory allocation (in MB)"
                    public:
                      type: boolean
                      description: "Whether the service is publicly accessible"
                    endpoint:
                      type: string
                      description: "Custom domain endpoint for public services (optional)"
                    deploy:
                      type: object
                      description: "Deployment configuration (optional)"
                      properties:
                        gitrepo:
                          type: string
                          description: "Git repository"
                        method:
                          type: string
                          enum: ["from_branch", "from_tag"]
                          description: "Deployment method"
                        branch:
                          type: string
                          description: "Branch to deploy from"
                        dockerfilepath:
                          type: string
                          description: "Path to Dockerfile"
