apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: envs.ktl.ai
spec:
  group: ktl.ai
  names:
    kind: Env
    plural: envs
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                services:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      image:
                        type: string
                      replicas:
                        type: integer
                      public:
                        type: boolean
                      port:
                        type: integer