apiVersion: apps/v1
kind: Deployment
metadata:
  name: kop
  namespace: {{ .Release.Namespace }}
  labels:
    app: kop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kop
  template:
    metadata:
      labels:
        app: kop
    spec:
      containers:
      - name: kop
        image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
        imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace