# templates/ingress.yaml
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: klient-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if eq .Values.cloudProvider "eks" }}
    {{- toYaml .Values.ingress.annotations.eks | nindent 4 }}
    {{- end }}
    {{- if eq .Values.cloudProvider "gke" }}
    {{- toYaml .Values.ingress.annotations.gke | nindent 4 }}
    {{- end }}
    {{- if eq .Values.cloudProvider "aks" }}
    {{- toYaml .Values.ingress.annotations.aks | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: klient
                port:
                  number: 80
{{- end }}
