# templates/service-klient.yaml
apiVersion: v1
kind: Service
metadata:
  name: klient
  namespace: {{ .Release.Namespace }}
  labels:
    app: klient
  annotations:
    {{- if eq .Values.cloudProvider "eks" }}
    {{- toYaml .Values.service.annotations.eks | nindent 4 }}
    {{- end }}
    {{- if eq .Values.cloudProvider "gke" }}
    {{- toYaml .Values.service.annotations.gke | nindent 4 }}
    {{- end }}
    {{- if eq .Values.cloudProvider "aks" }}
    {{- toYaml .Values.service.annotations.aks | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type | default "LoadBalancer" }}
  selector:
    app: klient
  ports:
    - name: http
      port: 80
      targetPort: 3000
