name: Publish -> GH Pages

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Package chart
        run: |
          mkdir -p pkg
          helm package . --destination pkg

      - name: Release to GitHub Pages
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: pkg
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Discord (success)
        if: success()
        run: |
          STATUS="✅ Helm chart published to GitHub Pages."
          COMMIT_MESSAGE=$(git log -1 --pretty=%B | sed 's/"/\\"/g')
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          COMMIT_AUTHOR="${{ github.actor }}"
          curl -H "Content-Type: application/json" \
            -d "{\"content\": \"${STATUS}\\n[${COMMIT_MESSAGE}](${COMMIT_URL}) - ${COMMIT_AUTHOR}\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify Discord (failure)
        if: failure()
        run: |
          STATUS="⚠️ Helm chart publish failed!"
          COMMIT_MESSAGE=$(git log -1 --pretty=%B | sed 's/"/\\"/g')
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          COMMIT_AUTHOR="${{ github.actor }}"
          curl -H "Content-Type: application/json" \
            -d "{\"content\": \"${STATUS}\\n[${COMMIT_MESSAGE}](${COMMIT_URL}) - ${COMMIT_AUTHOR}\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
