name: Publish Helm Chart to S3

on:
  release:
    types:
      - published
  workflow_dispatch:

env:
  REGION: us-west-2
  BUCKET: ktlai-install

jobs:
  deploy-helm-chart:
    name: Publish Helm Chart to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Chart Version
        id: get-version
        run: |
          export VERSION=$(grep '^version:' Chart.yaml | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_DEV_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_DEV_SECRET_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Helm Package
        run: |
          helm package . --destination helm-pkg --version $VERSION

      - name: Download existing index.yaml if it exists
        run: |
          if aws s3 ls s3://$BUCKET/helm-charts/index.yaml; then
            aws s3 cp s3://$BUCKET/helm-charts/index.yaml helm-pkg/index.yaml
          else
            echo "No existing index.yaml found, proceeding with a new one"
          fi

      - name: Update Helm Repository Index
        run: |
          if [ -s helm-pkg/index.yaml ]; then
            helm repo index helm-pkg --url https://$BUCKET.s3.$REGION.amazonaws.com/helm-charts --merge helm-pkg/index.yaml
          else
            helm repo index helm-pkg --url https://$BUCKET.s3.$REGION.amazonaws.com/helm-charts
          fi

      - name: Sync to S3
        run: |
          if [ ! -s helm-pkg/index.yaml ]; then
            echo "Error: index.yaml is empty or missing" >&2
            exit 1
          fi
          aws s3 sync helm-pkg/ s3://$BUCKET/helm-charts/ \
          --acl public-read \
          --delete
