
name: 
  Publish to S3 - Helm Chart

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

env:
  REGION: us-west-2
  BUCKET: ktlai-install

jobs:
  deploy-helm-chart:
    name: Publish to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_DEV_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_DEV_SECRET_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Helm Package
        run: |
          helm package .
          mkdir helm-pkg
          mv *.tgz helm-pkg/

      - name: Sync to S3
        run: |
          aws s3 sync helm-pkg/ s3://$BUCKET/helm-charts/ \
          --acl public-read \
          --delete
