name: Helm chart tests

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  kind-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Create kind cluster
        uses: helm/kind-action@v1.5.0
        with:
          cluster_name: ktl-ci

      - name: Install NGINX Ingress
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx && helm repo update
          helm install nginx ingress-nginx/ingress-nginx \
            --namespace ingress-nginx --create-namespace
          kubectl -n ingress-nginx wait --for=condition=Available deploy/nginx-ingress-nginx-controller --timeout=180s

      - name: Install KTL DevPortal chart
        run: |
          helm install ktl ./ktl \
            --namespace ktl --create-namespace \
            --set ingress.enabled=true \
            --set ingress.className=nginx \
            --set ingress.host=dev.ktl.local
          kubectl -n ktl rollout status deploy/klient --timeout=180s
          kubectl -n ktl rollout status deploy/kop --timeout=180s

      - name: Smoke tests
        run: |
          kubectl -n ingress-nginx port-forward svc/nginx-ingress-nginx-controller 8080:80 &
          PF=$!
          sleep 5
          echo "Checking / (expect 200)"
          [ "$(curl -s -o /dev/null -w '%{http_code}' http://localhost:8080/)" == "200" ]
          echo "Checking /api/environment/list (expect 200)"
          [ "$(curl -s -o /dev/null -w '%{http_code}' http://localhost:8080/api/environment/list)" == "200" ]
          kill $PF 